apiVersion: v1
kind: Secret
metadata:
  name: attendee-secrets
type: Opaque
stringData:
  POSTGRES_HOST: "changeme"
  POSTGRES_PORT: "changme"
  POSTGRES_USER: "changeme"
  POSTGRES_DB: "changeme"
  POSTGRES_PASSWORD: "changeme"
  REDIS_URL: "changeme"
  CREDENTIALS_ENCRYPTION_KEY: "changeme"
  DJANGO_SECRET_KEY: "changeme"
  AWS_RECORDING_STORAGE_BUCKET_NAME: "changeme"
  AWS_ACCESS_KEY_ID: "changeme"
  AWS_SECRET_ACCESS_KEY: "changeme"
  AWS_DEFAULT_REGION: "us-east-1"